# Metric collector template
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.collector.name }}
  namespace: {{ .Release.namespace }}
  labels: {{- include "pi-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pi-agent.collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pi-agent.collector.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--schedule"
            - "{{ .Values.collector.schedule }}"
          volumeMounts:
          - name: sysfs
            mountPath: /host/sys
            readOnly: true
          - name: procfs
            mountPath: /host/proc
            readOnly: true
          - name: rootfs
            mountPath: /host/root
            readOnly: true
      tolerations:
      # Run on all nodes including control plane
      - operator: Exists
      volumes:
      - name: sysfs
        hostPath:
          path: /sys
      - name: procfs
        hostPath:
          path: /proc
      - name: rootfs
        hostPath:
          path: /
